articles/urls.py
from django.urls import path

from articles.views import (
    article_search_view,
    article_detail_view,
    article_create_view) 

app_name='articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),
    ]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

# from accounts import views as accounts_view
from accounts.views import (
    login_view, 
    logout_view, 
    register_view)

from search.views import search_view
from .views import home_view

urlpatterns = [
    path('', home_view), # home /index/root
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view)
    ]

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view, 
    recipe_detail_view, 
    recipe_create_view,
    recipe_update_view,
    recipe_detail_hx_view, 
    recipe_ingredient_update_hx_view)


app_name='recipes'

urlpatterns = [
    path("", recipe_list_view, name='list'),
    path("create/", recipe_create_view, name='create'),
    path("hx/<int:parent_id>/ingredient/<int:id>/", recipe_ingredient_update_hx_view, name='hx-ingredient-detail'),
    path("hx/<int:parent_id>/ingredient/", recipe_ingredient_update_hx_view, name='hx-ingredient-create'),
    path("hx/<int:id>/", recipe_detail_hx_view, name='hx-detail'),
    path("<int:id>/edit/", recipe_update_view, name='update'),
    path("<int:id>/", recipe_detail_view, name='detail'),
]

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <script src="https://unpkg.com/htmx.org@1.5.0"></script>
        <style>
            .htmx-indicator {
                display: none;
            }
            .htmx-request .htmx-indicator {
                display: inline;
            }
            .htmx-inverted-indicator {
                display: inline;
            }
            .htmx-request .htmx-inverted-indicator {
                display: none;
            }
        </style>
    </head>
    <body>
        <h1>Heading</h1>
        {% include 'search/search-form.html' %}
        
        {% block content %}
        <h3>This will be replaced</h3>
        {% endblock content %}
    </body>
</html>

templates/home-view.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }} (id: {{ id }})!</h1>
<p>{{ content }}!</p>

<a href='{% url "articles:create" %}'>Create Article</a><br/>
<a href='{% url "articles:detail" slug="hi" %}'>Hi</a><br/>
<ul>
    {% for x in object_list %} 
        {% if x.title %}
        <li><a href='{{ x.get_absolute_url }}'>{{ x.title }} - {{ x.content }}</a></li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock content %}